###> JUST EXAMPLE, copy it into your config ###

gs_command:
    app_env: '%env(APP_ENV)%'
    
    #https://raw.githubusercontent.com/sindresorhus/cli-spinners/master/spinners.json
    progress_bar_spin:
    -    ⠋
    -    ⠙
    -    ⠹
    -    ⠸
    -    ⠼
    -    ⠴
    -    ⠦
    -    ⠧
    -    ⠇
    -    ⠏