monolog:
    channels:
    # service: @monolog.logger.gs_command.dev_logger
    -   "gs_command.dev_logger"

###> TODO: REALIZE IT IN YOUR monolog.yaml ###
when@dev:
    monolog:
        handlers:
            gs_command.dev_logger:
                type:           rotating_file
                max_files:      1
                path:           "%kernel.logs_dir%/gs_command_%kernel.environment%.log"
                level:          debug
                channels:       ["gs_command.dev_logger"]
###< TODO: REALIZE IT IN YOUR monolog.yaml ###